# Generated by Django 2.2.2 on 2019-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=140)),
                ('loaction', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('anouncedate', models.DateTimeField()),
                ('detail', models.TextField(max_length=140)),
                ('photo', models.FileField(upload_to='')),
                ('organizer', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
                ('posteddate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=140)),
                ('subject', models.CharField(max_length=140)),
                ('comment', models.CharField(max_length=140)),
            ],
        ),
    ]
