# Generated by Django 2.2.2 on 2019-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_auto_20190919_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(max_length=1400000000),
        ),
    ]
