# Generated by Django 3.0.2 on 2020-02-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
